# -*- coding: utf-8 -*-
import glob
import logging
import os
from datetime import datetime

from PyQt5 import QtCore, QtWidgets

# Form implementation generated from reading ui file 'c:\Programmation\Python\Cool Projects\CapytaleAutoCorrect\ui\window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

logger = logging.getLogger(__name__)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.copy_path = None
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleCard = CardWidget(self.centralwidget)
        self.TitleCard.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TitleCard.setObjectName("TitleCard")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.TitleCard)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TitleLabel = TitleLabel(self.TitleCard)
        self.TitleLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout_6.addWidget(self.TitleLabel)
        self.PushButton = PushButton(self.TitleCard)
        self.PushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_6.addWidget(self.PushButton)
        self.verticalLayout.addWidget(self.TitleCard)
        self.CardWidget = CardWidget(self.centralwidget)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TableView = TableWidget(self.CardWidget)
        self.TableView.setShowGrid(True)
        self.TableView.setSortingEnabled(True)
        self.TableView.setObjectName("TableView")
        self.horizontalLayout.addWidget(self.TableView)
        self.verticalLayout.addWidget(self.CardWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.TableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.retranslateUi(MainWindow)
        self.PushButton.clicked.connect(self.clicked)

    def set_copies_path(self, path):
        self.copies_path = path

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "Téléchargement des fichiers d\'élèves"))
        self.PushButton.setText(_translate("MainWindow", "Suivant"))

    def initialize_table(self):
        self.TableView.setColumnCount(3)
        self.TableView.setHorizontalHeaderLabels(["Nom de l'élève", "Date de téléchargement", "Nom du fichier"])

    def clicked(self):
        # empty the table
        self.TableView.setRowCount(0)
        self.initialize_table()
        path = self.copies_path
        logger.debug(path)
        # Load all the files in the directory

        try:
            files = glob.glob(f"{path}/*.py")
            files = [os.path.basename(file) for file in files]
        except FileNotFoundError:
            logger.error("Le dossier de copies n'a pas été trouvé")
            return
        logger.debug(files)
        # Sort them by date
        files.sort(key=lambda x: os.path.getmtime(os.path.join(path, x)))
        # Reverse the list to have the most recent files first
        files.reverse()

        logger.debug(files)
        # Add the files to the table
        for file in files:
            self.TableView.insertRow(0)
            self.TableView.setItem(0, 0, QtWidgets.QTableWidgetItem(file.split(".")[0]))
            timestamp = os.path.getmtime(os.path.join(path, file))
            datetime_obj = datetime.fromtimestamp(timestamp)
            hour_minute_string = datetime_obj.strftime('%H:%M')
            self.TableView.setItem(0, 1, QtWidgets.QTableWidgetItem(hour_minute_string))
            self.TableView.setItem(0, 2, QtWidgets.QTableWidgetItem(file))

        # Resize the columns to fit the content
        self.TableView.resizeColumnsToContents()

        # Resize the rows to fit the content
        self.TableView.resizeRowsToContents()


from qfluentwidgets import CardWidget, PushButton, TableWidget, TitleLabel
